name: Check Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ "${GITHUB_REF#refs/heads/}" != feat/* ]]; then
            echo "Branch name does not follow the 'feat/...' convention"
            exit 1
          fi
# error