name: Branch Name Convention

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Validate branch name
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" =~ ^feature\/.* || "$BRANCH_NAME" =~ ^bugfix\/.* || "$BRANCH_NAME" =~ ^release\/.* || "$BRANCH_NAME" =~ ^hotfix\/.* ]]; then
            echo "Branch name is valid: $BRANCH_NAME"
          else
            echo "Invalid branch name: $BRANCH_NAME"
            exit 1
          fi