name: Enforce Branch Naming Conventions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate branch name
        id: validate-branch-name
        uses: actions/toolkit@v3
        with:
          commands: |
            branch_name=$(git branch --show-current)
            if ! [[ $branch_name =~ ^(feat|hotfix|bugfix)/[A-Za-z0-9_-]+(/[A-Za-z0-9_-]+)*$ ]]; then
              echo "Invalid branch name: $branch_name"
              exit 1
            fi

      - name: Fail workflow if branch name is invalid
        if: steps.validate-branch-name.outcome != 'success'
        run: exit 1
# wrong